-- =============================================================================
-- DANIVISUAL SUPABASE DEPLOY SCRIPT
-- =============================================================================
-- Purpose: Master script that runs all SQL files in correct order
-- Usage: This file is meant to be run from terminal, not directly in SQL Editor
--
-- IMPORTANT: Do NOT run this file directly in Supabase SQL Editor!
-- Use the command line scripts instead:
--   - Windows: scripts/deploy-supabase.bat
--   - Mac/Linux: scripts/deploy-supabase.sh
-- =============================================================================

-- This file lists all SQL files that will be executed by the deployment scripts.
-- The actual \i commands are in the shell scripts, not here.

-- =============================================================================
-- FILE ORDER FOR DEPLOYMENT
-- =============================================================================
--
-- STEP 1: Core Schema Files (in order)
-- -----------------------------------
-- 1.1. schema.sql - Core tables (packages, faqs, content_menus, etc.)
-- 1.2. schema-auth.sql - Auth & admin_users table
-- 1.3. schema-admin.sql - Admin analytics tables
-- 1.4. schema-bookings.sql - Bookings & customers tables
-- 1.5. schema-operational.sql - Attendance, KPI, tasks
-- 1.6. schema-staff-management.sql - Staff management tables
-- 1.7. schema-staff-kpi.sql - Staff KPI tables
--
-- STEP 2: Additional Schema Files
-- -----------------------------------
-- 2.1. schema-inquiries.sql - Inquiries table
-- 2.2. schema-payment-accounts.sql - Payment accounts
--
-- STEP 3: RLS Policies (Security)
-- -----------------------------------
-- 3.1. rls-policies.sql - Row Level Security policies
--
-- STEP 4: Migrations (Security Hardening)
-- -----------------------------------
-- 4.1.  002_add_employee_user_linking.sql
-- 4.2.  003_attendance_settings.sql
-- 4.3.  004_align_staff_tasks_schema.sql
-- 4.4.  005_add_employee_info_to_attendance_records.sql
-- 4.5.  005_kpi_jobs.sql
-- 4.6.  006_customers_foundation.sql
-- 4.7.  007_inquiry_customer_conversion.sql
-- 4.8.  008_harden_finance_payments_rls.sql
-- 4.9.  009_bookings_archive_fields.sql
-- 4.10. 010_harden_bookings_rls.sql
-- 4.11. 011_harden_staff_tables_rls.sql
-- 4.12. 012_add_customers_auth_id_link.sql
-- 4.13. 013_harden_finance_and_staff_rls.sql
-- 4.14. 014_finance_customer_data_restriction.sql
-- 4.15. 015_add_attendance_selfies_bucket.sql
-- 4.16. 015_add_operational_staff_roles.sql
-- 4.17. 016_seed_production_users.sql (OPTIONAL - for testing)
--
-- STEP 5: Seed Data (Optional)
-- -----------------------------------
-- 5.1. seed-packages.sql
-- 5.2. seed-portfolio.sql
-- 5.3. seed-faqs-from-frontend.sql
-- 5.4. seed-portfolio-from-frontend.sql
--
-- =============================================================================

-- =============================================================================
-- NOTES
-- =============================================================================
--
-- 1. DO NOT hardcode any passwords or connection strings in this file
-- 2. All configuration should come from environment variables
-- 3. Run migrations in order - later migrations may depend on earlier ones
-- 4. Some migrations have IF NOT EXISTS checks for idempotency
-- 5. Check Supabase Dashboard > SQL Editor for manual verification
--
-- =============================================================================

-- This is a reference file only. The actual execution is done by shell scripts.